// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Infrastructure.Persistence;

#nullable disable

namespace Restaurant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Restaurant.Domain.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"), 1L, 1);

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaProducto", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("ABIERTA")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_apertura")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cierre");

                    b.Property<int>("IdMesa")
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    b.Property<int>("IdUsuarioApertura")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_apertura");

                    b.Property<int?>("IdUsuarioCierre")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_cierre");

                    b.Property<decimal>("Impuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("impuesto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.HasKey("IdCuenta");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Cuenta_Estado");

                    b.HasIndex("FechaCierre")
                        .HasDatabaseName("IX_Cuenta_FechaCierre");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdUsuarioApertura");

                    b.HasIndex("IdUsuarioCierre");

                    b.ToTable("Cuenta", (string)null);

                    b.HasCheckConstraint("CK_Cuenta_estado", "[estado] IN ('ABIERTA','CERRADA','ANULADA')");

                    b.HasCheckConstraint("CK_Cuenta_impuesto", "[impuesto] >= 0");

                    b.HasCheckConstraint("CK_Cuenta_subtotal", "[subtotal] >= 0");

                    b.HasCheckConstraint("CK_Cuenta_total", "[total] >= 0");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mesa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"), 1L, 1);

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<byte>("Capacidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("capacidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DISPONIBLE")
                        .HasColumnName("estado");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int")
                        .HasColumnName("numero_mesa");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdMesa");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Mesa_Estado");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesa", (string)null);

                    b.HasCheckConstraint("CK_Mesa_capacidad", "[capacidad] BETWEEN 1 AND 20");

                    b.HasCheckConstraint("CK_Mesa_estado", "[estado] IN ('DISPONIBLE','OCUPADA','EN_COBRO')");

                    b.HasCheckConstraint("CK_Mesa_numero", "[numero_mesa] > 0");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"), 1L, 1);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("FechaEnvioCocina")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_envio_cocina");

                    b.Property<DateTime?>("FechaListo")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_listo");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta");

                    b.Property<int>("IdUsuarioMesero")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_mesero");

                    b.Property<string>("ObservacionGeneral")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("observacion_general");

                    b.HasKey("IdPedido");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pedido_Estado");

                    b.HasIndex("FechaEnvioCocina")
                        .HasDatabaseName("IX_Pedido_FechaEnvioCocina");

                    b.HasIndex("IdUsuarioMesero");

                    b.HasIndex("IdCuenta", "FechaCreacion")
                        .HasDatabaseName("IX_Pedido_Cuenta_Fecha");

                    b.ToTable("Pedido", (string)null);

                    b.HasCheckConstraint("CK_Pedido_estado", "[estado] IN ('PENDIENTE','EN_PREPARACION','LISTO','CANCELADO')");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.PedidoDetalle", b =>
                {
                    b.Property<int>("IdPedidoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoDetalle"), 1L, 1);

                    b.Property<short>("Cantidad")
                        .HasColumnType("smallint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdPedidoDetalle");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("IX_PedidoDetalle_Pedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("PedidoDetalle", (string)null);

                    b.HasCheckConstraint("CK_PedidoDetalle_cantidad", "[cantidad] > 0");

                    b.HasCheckConstraint("CK_PedidoDetalle_precio", "[precio_unitario] >= 0");

                    b.HasCheckConstraint("CK_PedidoDetalle_subtotal", "[subtotal] >= 0");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<short?>("TiempoPreparacionMin")
                        .HasColumnType("smallint")
                        .HasColumnName("tiempo_preparacion_min");

                    b.HasKey("IdProducto");

                    b.HasIndex("Disponible")
                        .HasDatabaseName("IX_Producto_Disponible");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Producto", (string)null);

                    b.HasCheckConstraint("CK_Producto_precio", "[precio] >= 0");

                    b.HasCheckConstraint("CK_Producto_tiempo", "[tiempo_preparacion_min] >= 0");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"), 1L, 1);

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "UsuarioApertura")
                        .WithMany("CuentasAbiertas")
                        .HasForeignKey("IdUsuarioApertura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCierre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mesa");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "UsuarioMesero")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuarioMesero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("UsuarioMesero");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CuentasAbiertas");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
